apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secret-access
  namespace: cicd
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secret-access
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-secret-access
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: cicd
