apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: your-value
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  - name: node
    image: node:18
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
  - name: trivy
    image: aquasec/trivy:latest
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
