apiVersion: v1
kind: Pod
metadata:
  name: mernapp-pipeline
  namespace: cicd
  labels:
    jenkins: slave
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: http://jenkins.cicd.svc.cluster.local:8080
      ports:
        - containerPort: 50000
          name: jnlp
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "200m"

    - name: node
      image: node:18
      command:
        - sleep
        - "infinity"
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      # Supprimer la commande cat ou remplacer par sleep infinity
      command:
        - sleep
        - "infinity"
      tty: true

    - name: sonar-scanner
      image: sonarsource/sonar-scanner-cli:latest
      command:
        - sleep
        - "infinity"
      tty: true

    - name: trivy
      image: aquasec/trivy:latest
      command:
        - sleep
        - "infinity"
      tty: true

  restartPolicy: Never
