apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    env:
      - name: JENKINS_AGENT_WORKDIR
        value: /home/jenkins/agent
    ports:
      - containerPort: 50000  # Port JNLP fixe
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  - name: node
    image: node:18
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"

  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
      - cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"

  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"

  - name: trivy
    image: aquasec/trivy:latest
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"

  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred  # Le secret docker-registry pour kaniko
